version: '2'
services:
  revcalc-app:
    image: revcalc
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://revcalc-postgresql:5432/RevCalc
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  revcalc-postgresql:
    extends:
      file: postgresql.yml
      service: revcalc-postgresql
